services:
  mysql:
    image: mysql:8.0
    container_name: peergrade-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: peergradehub
      MYSQL_USER: peergrade
      MYSQL_PASSWORD: peergrade123
      MYSQL_ROOT_PASSWORD: peergrade_root123
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3307:3306"
    volumes:
      - peergrade_mysql_data:/var/lib/mysql

volumes:
  peergrade_mysql_data:
